# coding: utf-8

"""
    Process Dispatcher API

    Execute processes with the Process Dispatcher API.

    OpenAPI spec version: 0.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
    
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    
        http://www.apache.org/licenses/LICENSE-2.0
    
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ExecutionPatch(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ExecutionPatch - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'process_instance': 'int',
            'callback_url': 'str',
            'force_spawn_cluster': 'str',
            'resource_provisioner_token': 'str'
        }

        self.attribute_map = {
            'process_instance': 'process_instance',
            'callback_url': 'callback_url',
            'force_spawn_cluster': 'force_spawn_cluster',
            'resource_provisioner_token': 'resource_provisioner_token'
        }

        self._process_instance = None
        self._callback_url = None
        self._force_spawn_cluster = None
        self._resource_provisioner_token = None

    @property
    def process_instance(self):
        """
        Gets the process_instance of this ExecutionPatch.
        Unique ID of the process instance this execution is of

        :return: The process_instance of this ExecutionPatch.
        :rtype: int
        """
        return self._process_instance

    @process_instance.setter
    def process_instance(self, process_instance):
        """
        Sets the process_instance of this ExecutionPatch.
        Unique ID of the process instance this execution is of

        :param process_instance: The process_instance of this ExecutionPatch.
        :type: int
        """
        
        self._process_instance = process_instance

    @property
    def callback_url(self):
        """
        Gets the callback_url of this ExecutionPatch.
        URL called after completion of the job (possibly empty)

        :return: The callback_url of this ExecutionPatch.
        :rtype: str
        """
        return self._callback_url

    @callback_url.setter
    def callback_url(self, callback_url):
        """
        Sets the callback_url of this ExecutionPatch.
        URL called after completion of the job (possibly empty)

        :param callback_url: The callback_url of this ExecutionPatch.
        :type: str
        """
        
        self._callback_url = callback_url

    @property
    def force_spawn_cluster(self):
        """
        Gets the force_spawn_cluster of this ExecutionPatch.
        If set and not empty, forces the creation of a new cluster

        :return: The force_spawn_cluster of this ExecutionPatch.
        :rtype: str
        """
        return self._force_spawn_cluster

    @force_spawn_cluster.setter
    def force_spawn_cluster(self, force_spawn_cluster):
        """
        Sets the force_spawn_cluster of this ExecutionPatch.
        If set and not empty, forces the creation of a new cluster

        :param force_spawn_cluster: The force_spawn_cluster of this ExecutionPatch.
        :type: str
        """
        
        self._force_spawn_cluster = force_spawn_cluster

    @property
    def resource_provisioner_token(self):
        """
        Gets the resource_provisioner_token of this ExecutionPatch.
        Authentication token to be used to connect to the Resource Provisioner

        :return: The resource_provisioner_token of this ExecutionPatch.
        :rtype: str
        """
        return self._resource_provisioner_token

    @resource_provisioner_token.setter
    def resource_provisioner_token(self, resource_provisioner_token):
        """
        Sets the resource_provisioner_token of this ExecutionPatch.
        Authentication token to be used to connect to the Resource Provisioner

        :param resource_provisioner_token: The resource_provisioner_token of this ExecutionPatch.
        :type: str
        """
        
        self._resource_provisioner_token = resource_provisioner_token

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

